/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductImageDTO } from './product-image-dto';
/**
 * 
 * @export
 * @interface AddProductImagesDTO
 */
export interface AddProductImagesDTO {
    /**
     * 
     * @type {number}
     * @memberof AddProductImagesDTO
     */
    productId?: number;
    /**
     * 
     * @type {Array<ProductImageDTO>}
     * @memberof AddProductImagesDTO
     */
    productImages?: Array<ProductImageDTO>;
}
