/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BlogMetaData
 */
export interface BlogMetaData {
    /**
     * 
     * @type {string}
     * @memberof BlogMetaData
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogMetaData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogMetaData
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogMetaData
     */
    blogUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof BlogMetaData
     */
    viewCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BlogMetaData
     */
    likeCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof BlogMetaData
     */
    publishedDate?: Date;
}
