/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CommonResponse
 */
export interface CommonResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonResponse
     */
    type?: string | null;
}
