/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateReturn
 */
export interface CreateReturn {
    /**
     * 
     * @type {number}
     * @memberof CreateReturn
     */
    salesOrderId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateReturn
     */
    addressId?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateReturn
     */
    requestedPickupDate?: Date;
}
