/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateProduct
 */
export interface CreateProduct {
    /**
     * 
     * @type {string}
     * @memberof CreateProduct
     */
    sku?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProduct
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProduct
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProduct
     */
    brand?: string;
}
