/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum FilterOperation {
    In = 'In',
    Equals = 'Equals',
    LessThan = 'LessThan',
    Contains = 'Contains',
    NotEqual = 'NotEqual',
    EndsWith = 'EndsWith',
    StartsWith = 'StartsWith',
    GreaterThan = 'GreaterThan',
    LessThanOrEqual = 'LessThanOrEqual',
    GreaterThanOrEqual = 'GreaterThanOrEqual',
    Any = 'Any',
    All = 'All'
}

