/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetAccountOutputDTO } from './get-account-output-dto';
/**
 * 
 * @export
 * @interface GetAccountOutputDTOCommonResponse
 */
export interface GetAccountOutputDTOCommonResponse {
    /**
     * 
     * @type {GetAccountOutputDTO}
     * @memberof GetAccountOutputDTOCommonResponse
     */
    data?: GetAccountOutputDTO;
    /**
     * 
     * @type {number}
     * @memberof GetAccountOutputDTOCommonResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAccountOutputDTOCommonResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountOutputDTOCommonResponse
     */
    type?: string | null;
}
