/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Gender } from './gender';
/**
 * 
 * @export
 * @interface GetAccountOutputDTO
 */
export interface GetAccountOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof GetAccountOutputDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountOutputDTO
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountOutputDTO
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof GetAccountOutputDTO
     */
    birthDate?: Date;
    /**
     * 
     * @type {Gender}
     * @memberof GetAccountOutputDTO
     */
    gender: Gender;
    /**
     * 
     * @type {string}
     * @memberof GetAccountOutputDTO
     */
    instagramUserName: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountOutputDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountOutputDTO
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountOutputDTO
     */
    jobTitle: string;
}
