/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ImageVariantDTO
 */
export interface ImageVariantDTO {
    /**
     * 
     * @type {string}
     * @memberof ImageVariantDTO
     */
    thumbnail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageVariantDTO
     */
    xSmall?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageVariantDTO
     */
    small?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageVariantDTO
     */
    medium?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageVariantDTO
     */
    large?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageVariantDTO
     */
    xLarge?: string | null;
}
