/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PaymentMethodDTO
 */
export interface PaymentMethodDTO {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDTO
     */
    cardAssociation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDTO
     */
    cardFamily?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDTO
     */
    cardBankName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethodDTO
     */
    cardBankCode?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDTO
     */
    lastFourDigit?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentMethodDTO
     */
    isDefault?: boolean;
}
