/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ImageVariantDTO } from './image-variant-dto';
/**
 * 
 * @export
 * @interface ProductImageDTO
 */
export interface ProductImageDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductImageDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductImageDTO
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductImageDTO
     */
    extension?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductImageDTO
     */
    url?: string;
    /**
     * 
     * @type {ImageVariantDTO}
     * @memberof ProductImageDTO
     */
    variants?: ImageVariantDTO;
}
