/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SalesOrderDTO } from './sales-order-dto';
/**
 * 
 * @export
 * @interface SalesOrderDTODQBResultDTO
 */
export interface SalesOrderDTODQBResultDTO {
    /**
     * 
     * @type {Array<SalesOrderDTO>}
     * @memberof SalesOrderDTODQBResultDTO
     */
    data?: Array<SalesOrderDTO>;
    /**
     * 
     * @type {number}
     * @memberof SalesOrderDTODQBResultDTO
     */
    count?: number;
}
