/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LineItemFeedbackDTO } from './line-item-feedback-dto';
import { ProductDTO } from './product-dto';
import { SalesOrderLineItemState } from './sales-order-line-item-state';
/**
 * 
 * @export
 * @interface SalesOrderLineItemDTO
 */
export interface SalesOrderLineItemDTO {
    /**
     * 
     * @type {number}
     * @memberof SalesOrderLineItemDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof SalesOrderLineItemDTO
     */
    productId?: number;
    /**
     * 
     * @type {SalesOrderLineItemState}
     * @memberof SalesOrderLineItemDTO
     */
    state?: SalesOrderLineItemState;
    /**
     * 
     * @type {ProductDTO}
     * @memberof SalesOrderLineItemDTO
     */
    product?: ProductDTO;
    /**
     * 
     * @type {LineItemFeedbackDTO}
     * @memberof SalesOrderLineItemDTO
     */
    feedback?: LineItemFeedbackDTO;
}
