/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SalesOrderAddressDTO
 */
export interface SalesOrderAddressDTO {
    /**
     * 
     * @type {number}
     * @memberof SalesOrderAddressDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderAddressDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderAddressDTO
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderAddressDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderAddressDTO
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderAddressDTO
     */
    zipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderAddressDTO
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderAddressDTO
     */
    district?: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderAddressDTO
     */
    fullAddress?: string;
}
