/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ShipSalesOrder
 */
export interface ShipSalesOrder {
    /**
     * 
     * @type {number}
     * @memberof ShipSalesOrder
     */
    salesOrderId?: number;
    /**
     * 
     * @type {string}
     * @memberof ShipSalesOrder
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShipSalesOrder
     */
    cargoState?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShipSalesOrder
     */
    cargoTrackingCode?: string | null;
}
