/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SalesOrderState } from './sales-order-state';
/**
 * 
 * @export
 * @interface ShipSalesOrderDTO
 */
export interface ShipSalesOrderDTO {
    /**
     * 
     * @type {number}
     * @memberof ShipSalesOrderDTO
     */
    id?: number;
    /**
     * 
     * @type {SalesOrderState}
     * @memberof ShipSalesOrderDTO
     */
    state?: SalesOrderState;
    /**
     * 
     * @type {Date}
     * @memberof ShipSalesOrderDTO
     */
    shippedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShipSalesOrderDTO
     */
    cargoState?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShipSalesOrderDTO
     */
    cargoTrackingCode?: string | null;
}
