/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BodyType } from './body-type';
/**
 * 
 * @export
 * @interface SizeInfoDTO
 */
export interface SizeInfoDTO {
    /**
     * 
     * @type {BodyType}
     * @memberof SizeInfoDTO
     */
    bodyType?: BodyType;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    upperBody?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    lowerBody?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    womenUnderWearCup?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    womenUnderWearSize?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    menUnderWear?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    outWear?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    footWear?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    additionalNotes?: string;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    shoulderWidth?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    headRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    armLength?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    bodyLength?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    neckRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    breastRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    waistRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    hipRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    legLength?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    footLength?: number;
}
