/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SizeInfoDTO
 */
export interface SizeInfoDTO {
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    tshirt?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    sweater?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    sweatshirt?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    crop?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    blouse?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    shirt?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    sleevelessUnderShirt?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    bustier?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    bralet?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    tunik?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    dress?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    overalls?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    pants?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    jeans?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    skirt?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    shorts?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    leggings?: string;
    /**
     * 
     * @type {string}
     * @memberof SizeInfoDTO
     */
    sweatpants?: string;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    neckRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    breastRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    waistRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    hipRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof SizeInfoDTO
     */
    legLength?: number;
}
