/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StylePreferencesDTO
 */
export interface StylePreferencesDTO {
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    choiceReasons?: string;
    /**
     * 
     * @type {number}
     * @memberof StylePreferencesDTO
     */
    lovesShopping?: number;
    /**
     * 
     * @type {number}
     * @memberof StylePreferencesDTO
     */
    openToSuggestions?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StylePreferencesDTO
     */
    prefersHijabClothing?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    bodyPartsToHighlight?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    bodyPartsToHide?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    excludedUpperCategories?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    excludedLowerCategories?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    excludedOuterCategories?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    excludedUnderwearCategories?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    excludedAccessoryCategories?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    excludedFootwearCategories?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StylePreferencesDTO
     */
    excludedBagCategories?: string | null;
}
