/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UpdateAccountOutputDTO } from './update-account-output-dto';
/**
 * 
 * @export
 * @interface UpdateAccountOutputDTOCommonResponse
 */
export interface UpdateAccountOutputDTOCommonResponse {
    /**
     * 
     * @type {UpdateAccountOutputDTO}
     * @memberof UpdateAccountOutputDTOCommonResponse
     */
    data?: UpdateAccountOutputDTO;
    /**
     * 
     * @type {number}
     * @memberof UpdateAccountOutputDTOCommonResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountOutputDTOCommonResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountOutputDTOCommonResponse
     */
    type: string;
}
