/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpsertFitPreferences
 */
export interface UpsertFitPreferences {
    /**
     * 
     * @type {string}
     * @memberof UpsertFitPreferences
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertFitPreferences
     */
    waistHeight?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertFitPreferences
     */
    upperFit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertFitPreferences
     */
    lowerFit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertFitPreferences
     */
    legFit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertFitPreferences
     */
    skirtDressLength?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertFitPreferences
     */
    shortsLength?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertFitPreferences
     */
    footType?: string | null;
}
