/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BodyType } from './body-type';
import { Gender } from './gender';
/**
 * 
 * @export
 * @interface UpsertSizeInfo
 */
export interface UpsertSizeInfo {
    /**
     * 
     * @type {Gender}
     * @memberof UpsertSizeInfo
     */
    gender?: Gender;
    /**
     * 
     * @type {BodyType}
     * @memberof UpsertSizeInfo
     */
    bodyType?: BodyType;
    /**
     * 
     * @type {string}
     * @memberof UpsertSizeInfo
     */
    upperBody?: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertSizeInfo
     */
    lowerBody?: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertSizeInfo
     */
    womenUnderWearCup?: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertSizeInfo
     */
    womenUnderWearSize?: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertSizeInfo
     */
    menUnderWear?: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertSizeInfo
     */
    outWear?: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertSizeInfo
     */
    footWear?: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertSizeInfo
     */
    additionalNotes?: string;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    shoulderWidth?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    headRadius?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    armLength?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    bodyLength?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    neckRadius?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    breastRadius?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    waistRadius?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    hipRadius?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    legLength?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertSizeInfo
     */
    footLength?: number | null;
}
