/* tslint:disable */
/* eslint-disable */
/**
 * ModilistAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface V1MessageSendEmailWithAttachmentsBody
 */
export interface V1MessageSendEmailWithAttachmentsBody {
    /**
     * 
     * @type {string}
     * @memberof V1MessageSendEmailWithAttachmentsBody
     */
    templateId?: string;
    /**
     * 
     * @type {string}
     * @memberof V1MessageSendEmailWithAttachmentsBody
     */
    senderName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1MessageSendEmailWithAttachmentsBody
     */
    from?: string;
    /**
     * 
     * @type {string}
     * @memberof V1MessageSendEmailWithAttachmentsBody
     */
    to?: string;
    /**
     * 
     * @type {string}
     * @memberof V1MessageSendEmailWithAttachmentsBody
     */
    templateData?: string;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof V1MessageSendEmailWithAttachmentsBody
     */
    attachments?: Array<Blob>;
}
